- assembler/bsc_assembler.go
- executor/greenfield_executor.go
- metric/metric_service.go
- vote/bsc_vote_processor.go
- vote/greenfield_vote_processor.go
this pr fixes that should not switch client when broadcast txs
nonce increment would fail.
NA
* NA
> fix: should not switch client for batchtx

- config/config.go
Perform wording change for binance related terms
none
none
Notable changes: 
none
> chore: bnb wording change

- assembler/bsc_assembler.go
- assembler/greenfield_assembler.go
Currently when the outturn relayer relying batch of tx, it gets the `endsequence` from DB which is lateset tx with status `all-voted` sequence,  this causes a problem that when the out-turn relayer become inturn, and if such tx is not submitted to BSC yet, the inturn relayer would relay it and record the tx with status `delivery` in DB if no error return. When the in-turn relayer become outturn again. If there is no new tx stored in DB, then the `endsequence` would always be 0 and no retry would happen.
So, should change to only rely on chain's updated sequence.
* ...
> fix: outturn relayer should only rely on chain's sequence

- metric/metric_service.go
> feat: add labels

- assembler/bsc_assembler.go
- assembler/greenfield_assembler.go
- common/const.go
- metric/service.go
this pr fix relayer alert for crosschain laggy tx
* ...
> fix: alert for crosschain laggy tx

- executor/bsc_executor.go
> fix: fix err not handled

- executor/bsc_executor.go
prepare for release v0.2.4-hf.1, fix a bug.
* https://github.com/bnb-chain/greenfield-relayer/pull/84
> release: prepare for v0.2.4-hf.1

- assembler/bsc_assembler.go
Remove the err type check since it's done in go-sdk.
* ...
> fix: fix a broadcast tx err issue

- assembler/greenfield_assembler.go
- executor/bsc_executor.go
- executor/const.go
- metric/service.go
- vote/greenfield_vote_processor.go
> fix: fix a err return

- common/const.go
extend the waiting time when catch up latest block to avoid annoying log
* ...
> fix: latest blcok err

- executor/bsc_executor.go
> feat: use dynamic gas price

- app/app.go
- config/const.go
- executor/bsc_executor.go
liveness check and use db cred by env var
* ...
> fix: liveness check and use db cred by env var

- app/app.go
- config/const.go
- main.go
read db username from env
* ...
> chore: read db username from env

- listener/bsc_listener.go
add a description of your changes here...
* ...
> fix: fix filter log compatibility

- executor/const.go
- executor/greenfield_executor.go
- executor/greenfield_executor_test.go
adjusted gas for submiting large crosschain pacakges
* ...
> feat: adjusted gas for large tx

- listener/greenfield_listener.go
> fix: sync light block header

- executor/bsc_executor.go
- listener/bsc_listener.go
et rid of block hash check
* ...
> feat: get rid of block hash check

- listener/greenfield_listener.go
Reverts bnb-chain/greenfield-relayer#108
> Revert "fix: sync light block header"

- listener/greenfield_listener.go
> fix: panic if tx mismatch 

- executor/const.go
add a description of your changes here...
* ...
> fix: extend timeout to 10 sec
